project:
  type: website

website:
  title: "AWS RE/START"
  navbar:
    left:
      - text: "Fundamentos de la Nube"
        file: Fundamentos-Nube/Fundamentos.qmd

      - text: "Linux"
        menu:
          - text: "Conceptos"
            file: Linux/conceptos.qmd
          - text: "Laboratorios"
          - text: "225 - Lab - Introducción a Linux Amazon AMI"
            file: Linux/255-LX-Lab.qmd
          - text: "227 - [LX] - Línea de comandos de Linux"
            file: Linux/227-LX-Lab.qmd
          - text: "229 - [LX] - Usuarios y grupos"
            file: Linux/229-LX-Lab.qmd
          - text: "231 - [LX] - Edición de archivos"
            file: Linux/231-LX-Lab.qmd
          - text: "233 - [LX] - Sistema de archivos Linux"
            file: Linux/233-LX-Lab.qmd
          - text: "235 - [LX] - Trabajo con archivos"
            file: Linux/235-LX-Lab.qmd
          - text: "237 - [LX] - Permisos de archivos"
            file: Linux/237-LX-Lab.qmd
          - text: "239 - [LX] - Procesos administrativos"
            file: Linux/239-LX-Lab.qmd
          - text: "241 - [LX] - Administración de servicios"
            file: Linux/241-LX-Lab.qmd
          - text: "243 - [LX] - Administración de software"
            file: Linux/243-LX-Lab.qmd
          - text: "245 - [LX] - Archivos de registro"
            file: Linux/245-LX-Lab.qmd
          - text: "247 - [LX] - Trabajo con comandos"
            file: Linux/247-LX-Lab.qmd
          - text: "249 - [LX] - El Bash Shell"
            file: Linux/249-LX-Lab.qmd
          - text: "251 - [LX] - Scripts de Bash Shell"
            file: Linux/251-LX-Lab.qmd
          - text: "253 - [LX] - Reto: Scripting Shell"
            file: Linux/253-LX-Lab.qmd

      - text: "Redes"
        menu:
          - text: "Conceptos"
            file: Redes/conceptos.qmd
          - text: "Lab[261]-IPs-publicas y privadas"
            file: Redes/Lab[261]-IPSpublicas y privadas.qmd
          - text: "Lab[262]-Direcciones IP y estáticas y dinámicas" 
            file: Redes/Lab[262]-Direcciones IP y estáticas y dinámicas.qmd
          - text: "Lab[263]-Creación de subredes y asignación de direcciones IP (VPC)"
            file: Redes/Lab[263]-Creación de subredes y asignación de direcciones IP (VPC).qmd
          - text: "Lab[264] - Recursos de red para una VPC"
            file: Redes/Lab[264]-Recursos de red para una VPC.qmd
          - text: "Lab[265]Comandos de solución de problemas del protocolo de Internet"
            file: Redes/Lab[265].qmd

      - text: "Seguridad"
        file: Seguridad/conceptos.qmd

      - text: "Python"
        file: Python/index.qmd
 
      - text: "Bases de Datos"
        file: Bases-Datos/index.qmd

      # - text: "Jumpstart AWS"
      #   file: Jumpstart-aws/index.qmd

      # - text: "Soft Skills"
      #   file: SoftSkills/index.qmd

      - text: "AWS Cloud Practitioner"
        menu:
          - text: "Training"
            menu:
              - text: "Examen Práctico 1"
                file: Training/practice-exam-1.qmd
              - text: "Examen Práctico 2"
                file: Training/practice-exam-2.qmd
              - text: "Examen Práctico 3"
                file: Training/practice-exam-3.qmd
              - text: "Examen Práctico 4"
                file: Training/practice-exam-4.qmd
              - text: "Examen Práctico 5"
                file: Training/practice-exam-5.qmd
              - text: "Examen Práctico 6"
                file: Training/practice-exam-6.qmd
              - text: "Examen Práctico 7"
                file: Training/practice-exam-7.qmd
              - text: "Examen Práctico 8"
                file: Training/practice-exam-8.qmd
              - text: "Examen Práctico 9"
                file: Training/practice-exam-9.qmd
              - text: "Examen Práctico 10"
                file: Training/practice-exam-10.qmd
              - text: "Examen Práctico 11"
                file: Training/practice-exam-11.qmd
              - text: "Examen Práctico 12"
                file: Training/practice-exam-12.qmd
              - text: "Examen Práctico 13"
                file: Training/practice-exam-13.qmd
              - text: "Examen Práctico 14"
                file: Training/practice-exam-14.qmd
              - text: "Examen Práctico 15"
                file: Training/practice-exam-15.qmd
              - text: "Examen Práctico 16"
                file: Training/practice-exam-16.qmd
              - text: "Examen Práctico 17"
                file: Training/practice-exam-17.qmd
              - text: "Examen Práctico 18"
                file: Training/practice-exam-18.qmd
              - text: "Examen Práctico 19"
                file: Training/practice-exam-19.qmd
              - text: "Examen Práctico 20"
                file: Training/practice-exam-20.qmd
      # - text: "Recursos"
      #   menu:
      #     - text: "Proyectos"
      #       file: Recursos/proyectos.qmd
      #     - text: "Píldoras"
      #       file: Recursos/pildoras.qmd
      #     - text: "Grabaciones"
      #       file: Recursos/grabaciones.qmd

    right:
      - icon: github
        href: https://github.com/borizSam
        aria-label: GitHub

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toggle:
      icon: moon-stars
      title: "Cambiar tema"
    toc: true
    toc-depth: 3
    number-sections: true
    css: styles.css
